### ISSUE TITLE
[BUG] Comments don't work.

### ISSUE THREAD

**Issue by The-Inamati** [khusika/FeelIt#75]
### Describe the bug

I'm trying to enable comments with vssue but it's not working. I created an OAuth App in Github according to their documentation. I edited the config.toml file with the client ID and secret but it still doesn't work. It says "failed to load comments". I also tried with telegram and gittalk and didn't work so I'm pretty sure I'm doing something wrong. Can anybody help?

### Expected behavior

I expected the comments to work.

**Comment by lewisdenny** [comment]
Yeah I was unable to get the telegram comments working on my site following the documentation +1 

Happy to help with testing.

**Comment by The-Inamati** [comment]
I have now tried all of them and none worked.

**Comment by khusika** [comment]
> I'm not. I'm running on a custom domain.

Make sure to enable this config
```
    [params.page.comment]
      enable = true
```

**Comment by lewisdenny** [comment]
Hey khusika,

Just to be clear this is all you are enabling to get Telegram comments working?

~~~
[params.page.comment]
  enable = true
  [params.page.comment.telegram]
    enable = true
    siteID = "********"
    limit = 5
    height = ""
    color = ""
    colorful = true
    dislikes = true
    outlined = false
~~~

Because this still isn't working for me, I even tried enabling comments directly on the content page with:
~~~
comment:
  enable: true
~~~

Do you have any example sites using your theme with Telegram comments and public configs I could compare with?

**Comment by eyllanesc** [comment]
> I just tried using `comment.vssue` from the example site with no luck so it must be something on my side. Is it a requirement that my site use https for comments to work?

Use `-e production` option.

**Comment by khusika** [comment]
Closed because there is no problem with the comments system
